### PR TITLE
fix: game_store bugs. fix: #873

### LINKED ISSUE #873: buy button gamestore inactive even though you have enough coins in your account
### Priority

Low

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

The buy button in gamestore is inactive even though you have enough coins in your account.
only Transferable Coins are working.
image

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kokekanon**
# Description

- Add HTTP image support (The main repo reduces by 20 MB.)

image

- update information once you buy
- call in lua `onParseStoreError` when there is an error in store appears in a displayErrorBox
image

- a displayErrorBox informing that the support to buy some items is not yet available because the UI is missing.

image

- support multiple coins: 

image
if you want test: 
canary\data\modules\scripts\gamestore\gamestore.lua
image

## Fixes

#873 

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: modules/game_store/game_store.lua [hunk 1]
```diff
@@ -162,10 +170,45 @@ GameStore.DefaultValues = {
 -- /*=============================================
 -- =            Local Function                  =
 -- =============================================*/
+local function setImagenHttp(widget, url,isIcon)
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
local function setImagenHttp(widget, url, isIcon)
```

File: modules/game_store/game_store.lua [hunk 2]
```diff
@@ -162,10 +170,45 @@ GameStore.DefaultValues = {
...
+    if Services and Services.store  then
+        HTTP.downloadImage(Services.store..url, function(path, err)
+            if err then
+                g_logger.warning("HTTP error: " .. err .. " - " .. Services.store..url)
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
                g_logger.warning("HTTP error: " .. err .. " - " .. Services.store .. url)
```

File: modules/game_store/game_store.lua [hunk 3]
```diff
@@ -162,10 +170,45 @@ GameStore.DefaultValues = {
 -- /*=============================================
 -- =            Local Function                  =
 -- =============================================*/
+local function setImagenHttp(widget, url,isIcon)
+    if Services and Services.store  then
+        HTTP.downloadImage(Services.store..url, function(path, err)
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
        HTTP.downloadImage(Services.store .. url, function(path, err)
```

File: modules/game_store/game_store.lua [hunk 4]
```diff
@@ -162,10 +170,45 @@ GameStore.DefaultValues = {
...
+            if err then
+                g_logger.warning("HTTP error: " .. err .. " - " .. Services.store..url)
+                if isIcon then
+                    widget:setIcon("/game_store/images/dynamic-image-error")
+                else
+                    widget:setImageSource("/game_store/images/dynamic-image-error")
+                    widget:setImageFixedRatio(false)
+                end
+
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
```

File: modules/game_store/game_store.lua [hunk 5]
```diff
@@ -286,7 +334,7 @@ end
 local function createSubWidget(parent, subId, subButton)
     local subWidget = g_ui.createWidget("storeCategory", parent)
     subWidget:setId(subId)
-    subWidget.Button.Icon:setIcon(subButton.icon)
+    setImagenHttp(subWidget.Button.Icon,subButton.icon,true)
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
    setImagenHttp(subWidget.Button.Icon, subButton.icon, true)
```

File: modules/game_store/game_store.lua [hunk 6]
```diff
@@ -334,7 +383,8 @@ local function createProductImage(imageParent, data)
         itemWidget:fill('parent')
     elseif data.VALOR == "icon" then
         local widget = g_ui.createWidget('UIWidget', imageParent)
-        widget:setImageSource("/game_store/images/64/" .. data.ID)
+       -- widget:setImageSource("/game_store/images/64/" .. data.ID)
+        setImagenHttp(widget,"/64/"..data.ID,false)
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
        setImagenHttp(widget,"/64/" .. data.ID, false)
```

File: modules/game_store/game_store.lua [hunk 7]
```diff
@@ -514,22 +583,19 @@ function onParseStoreCreateHome(offer)
...
         if data then
             createProductImage(row:getChildById('image'), data)
         end
     end
 
-    local imagenAleatoria = offer.banners[math.random(1, #offer.banners)].image
-    controllerShop.ui.HomePanel.HomeImagen:setImageSource("/game_store/images/" .. imagenAleatoria)
+    local ramdomImg = offer.banners[math.random(1, #offer.banners)].image
+   -- controllerShop.ui.HomePanel.HomeImagen:setImageSource("/game_store/images/" .. ramdomImg)
+    setImagenHttp(controllerShop.ui.HomePanel.HomeImagen,ramdomImg,false)
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
    setImagenHttp(controllerShop.ui.HomePanel.HomeImagen, ramdomImg, false)
```

File: modules/game_store/game_store.lua [hunk 8]
```diff
@@ -606,7 +672,13 @@ function onParseStoreGetCategories(buttons)
         if category then
             local widget = g_ui.createWidget("storeCategory", controllerShop.ui.listCategory)
             widget:setId(category.name)
-            widget.Button.Icon:setIcon("/game_store/images/13/" .. category.icons[1])
+            --widget.Button.Icon:setIcon("/game_store/images/13/" .. category.icons[1])
+            if category.icons[1] == "icon-store-home.png" then
+                widget.Button.Icon:setIcon("/game_store/images/icon-store-home")
+            else
+                setImagenHttp(widget.Button.Icon,"/13/"..category.icons[1],true)
```
Comment (luanluciano93) [inline modules/game_store/game_store.lua]:
```suggestion
                setImagenHttp(widget.Button.Icon,"/13/" .. category.icons[1], true)
```

**Review by luanluciano93 — CHANGES_REQUESTED** [review]

**Review by luanluciano93 — APPROVED** [review]
