### PR TITLE
fix: buy xp boost in gamestore

### LINKED ISSUE #1308: Game Store dont refresh skills UI after buying XP Boost
### Priority

Low

### Area

- [ ] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

Right now, it has been identified that buying an XP Boost in-store will not update timings on the skills UI tooltip.
Also, the XP percentage looks incorrect when no XP Boost is active.

https://github.com/user-attachments/assets/0df0982c-51ad-4a28-ad4e-9b0262233b52

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Juanzitooh**
# Description

This PR fixes two issues in the store system related to **xp boost purchases**:  
- The store UI was not refreshing immediately after purchasing an xp boost.  
- The amount displayed when trying to buy a boost could be incorrect.  

These fixes ensure correct values are shown to the player and the store reflects the updated state right away.

### **Actual**
- After buying an xp boost, the store did not update to reflect the purchase.  
- The displayed amount when attempting to buy a boost was wrong.  

### **Expected**
- After buying an xp boost, the store should update immediately.  
- The displayed amount when buying a boost should always be correct.  

## Fixes
No GitHub issue linked.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested
- Manual testing on local environment.  
- Bought xp boost multiple times and confirmed store updates correctly.  
- Verified that the displayed amount matches the actual purchase.  

**Test Configuration**:
- **Server Version:** Canary  
- **Client:** OTClient  
- **Operating System:** Windows 10 Pro x64  

## Checklist
- [x] My code follows the style guidelines of this project  
- [x] I have performed a self-review of my own code  
- [x] I checked the PR checks reports  
- [x] I have commented my code, particularly in hard-to-understand areas  
- [ ] I have made corresponding changes to the documentation  
- [x] My changes generate no new warnings  
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by libergod — APPROVED** [review]
Thank you for your contribution. This PR, aligned with the others from the game store, will improve the OTC usability!

File: modules/game_store/game_store.lua [hunk 1]
```diff
@@ -481,6 +481,7 @@ function onParseStoreGetPurchaseStatus(purchaseStatus)
                 animationEvent = nil
             end
             fixServerNoSend0xF2()
+            g_game.sendRequestStorePremiumBoost() --reabrir a store para parar de bugar a compra da xpboost
```
Comment (libergod) [inline modules/game_store/game_store.lua]: Please translate important info back to English; if not, please remove comments.

File: modules/game_store/game_store.lua [hunk 2]
```diff
@@ -902,8 +903,10 @@ function chooseOffert(self, focusedChild)
         local priceLabel = offerPanel:getChildById('lblPrice')
         priceLabel:setText(offer.price)
 
-        if offer.count and offer.count > 0 then
-            offerPanel:getChildById('btnBuy'):setText("Buy " .. offer.count .. "x")
+        -- 👇 Ajuste: garantir que nunca apareça "0x"
```
Comment (libergod) [inline modules/game_store/game_store.lua]: Please translate important info back to English; if not, please remove comments. Also, remove emoticons.

File: modules/game_store/game_store.lua [hunk 3]
```diff
@@ -997,22 +1001,37 @@ function chooseOffert(self, focusedChild)
...
-                },
+            local coinType = isTransferable and "transferable coins" or "regular coins"
+            local confirmationMessage = string.format(
+                'Do you want to buy the product "%s" for %d %s?', 
+                product.name, 
+                offer.price, 
+                coinType
+            )
+
+            -- 👇 aqui normalizamos o count
```
Comment (libergod) [inline modules/game_store/game_store.lua]: Please translate important info back to English; if not, please remove comments. Also, remove emoticons.

**Review by libergod — CHANGES_REQUESTED** [review]
Please translate important info back to English; if not, please remove comments. Also, remove emoticons.

**Comment by Juanzitooh** [comment]
ok, I change

**Review by libergod — APPROVED** [review]
Thank you for your contribution!
