### PR TITLE
feat: Vips Groups | fix issue: #730

### LINKED ISSUE #730: Vip list group
### Priority

Missing Content

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

image

The feature `Otc::GameVipGroups` is not implemented, as shown below:

image
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kokekanon**
# test in:
- canary 
- https://github.com/otland/forgottenserver/pull/4138

# Description

In simple tests it works, I do not rule out future corrections if someone finds any bugs.

image
image
image

image

I changed it to controller to facilitate reload
### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

#730 26 March 2024 

## Type of change

  - [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested

onVipStateChange offline , online 
onAddVip
create , edit , remove  grupos
Edit , remove, add player

**Test Configuration**:

  - Server Version: 860 and 1340
  - Client: this pr
  - Operating System: windows 10
 
## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

I updated the readme, if you want I will do it in another pr. but it is not a big change.

### CODE REVIEW

File: src/client/protocolgameparse.cpp [hunk 1]
```diff
@@ -2682,15 +2683,17 @@ void ProtocolGame::parseVipAdd(const InputMessagePtr& msg)
...
 
     const uint32_t status = msg->getU8();
-
+    std::vector<uint8_t> groupIDs;
     if (g_game.getFeature(Otc::GameVipGroups)) {
         const uint8_t vipGroupSize = msg->getU8();
+        groupIDs.reserve(vipGroupSize);
         for (auto i = 0; i < vipGroupSize; ++i) {
-            msg->getU8(); // Group ID
+            uint8_t groupID = msg->getU8();
```
Comment (luanluciano93) [inline src/client/protocolgameparse.cpp]:
```suggestion
            const uint8_t groupID = msg->getU8();
```

File: src/client/protocolgamesend.cpp [hunk 2]
```diff
@@ -830,14 +830,46 @@ void ProtocolGame::sendRemoveVip(const uint32_t playerId)
...
+        }
+    }
+    send(msg);
+}
+
+void ProtocolGame::sendEditVipGroups(const Otc::GroupsEditInfoType_t action, const uint8_t groupId, const std::string_view groupName)
+{
+    const auto& msg = std::make_shared<OutputMessage>();
+    msg->addU8(Proto::ClientEditVipGroups);
+    msg->addU8(action);
```
Comment (luanluciano93) [inline src/client/protocolgamesend.cpp]:
```suggestion
    msg->addU8(static_cast<uint8_t>(action));
```

File: src/client/game.cpp [hunk 3]
```diff
@@ -1243,9 +1249,22 @@ void Game::editVip(const uint32_t playerId, const std::string_view description,
...
+        }
+    }
+}
 
-    if (getFeature(Otc::GameAdditionalVipInfo))
-        m_protocolGame->sendEditVip(playerId, description, iconId, notifyLogin);
+void Game::editVipGroups(const Otc::GroupsEditInfoType_t action, const uint8_t groupId, const std::string_view groupName)
+{
+    if (!canPerformGameAction())
+        return;
```
Comment (luanluciano93) [inline src/client/game.cpp:1266]:
```suggestion
        return;

```

File: modules/game_viplist/viplist.lua [hunk 4]
```diff
@@ -4,23 +4,43 @@ addVipWindow = nil
...
+        onVipGroupChange = onVipGroupChange
+    })
 
-    if not g_game.getFeature(GameAdditionalVipInfo) then
-        loadVipInfo()
+    local settings = g_settings.getNode('VipList')
+    if settings then
+        globalSettings.showGrouped = settings['Grouped'] or false
+        globalSettings.hideOfflineVips = settings['OfflineVips'] or false
+        globalSettings.vipSortOrder = {}
```
Comment (luanluciano93) [inline modules/game_viplist/viplist.lua]:
```suggestion
       globalSettings.showGrouped = settings['Grouped'] or false
       globalSettings.hideOfflineVips = settings['OfflineVips'] or false
       globalSettings.vipSortOrder = {}
```

**Review by luanluciano93 — CHANGES_REQUESTED** [review]

**Review by luanluciano93 — APPROVED** [review]
