### PR TITLE
fix http timeout problems

### LINKED ISSUE #1198: HTTP.getJson doesnt work
### Priority

High

### Area

- [ ] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

Calling HTTP.getJson with url that returns json data, returns content length followed by newline and then the json, which doesn't go through the json.decode validation and errors.

`JSON ERROR: /corelib/json.lua:178: trailing garbage at line 2 col 1 (548`

Used url:
```
https://discord.com/api/v9/invites/WBMSR4qAzF?with_counts=true
```

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nekiro**
# Description

- fixed some errors with http client
- we are now requesting HTTP 1.0, because we do not support chunked encoding
- lowered timeouts a bit
- there are problems with ipv6 too, so we will now just look for ipv4 to use instead
- added debug logs to identify problems faster

### **Actual**

transfer-encoding: chunked is not supported and we send that we support HTTP 1.1 which is incorrect.
timeout doesn't work at all, if response doesn't finish it will never resolve, thus the http thread is stuck and never finishes

### **Expected**

Should properly parse json responses and thread should not get stuck.

## Fixes

#1198
#1242

## Type of change

Please delete options that are not relevant.

  - [x] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: modules/corelib/http.lua [hunk 1]
```diff
@@ -1,5 +1,5 @@
 HTTP = {
-  timeout = 60,
+  timeout = 2,
```
Comment (libergod) [inline modules/corelib/http.lua:2]: Does we need to rollback to 60 after tests?

File: src/framework/net/protocolhttp.cpp [hunk 2]
```diff
@@ -58,7 +59,7 @@ void Http::terminate()
 int Http::get(const std::string& url, int timeout)
 {
     if (!timeout) // lua is not working with default values
-        timeout = 5;
+        timeout = 2;
```
Comment (libergod) [inline src/framework/net/protocolhttp.cpp:62]: Do we need to rollback to 5 after tests?

File: modules/corelib/http.lua (hunk 1 above)
Comment (nekiro) [reply modules/corelib/http.lua:2]: no, timeout is in seconds, that 60 is a minute timeout, 2s is more than enough for request to complete.

File: src/framework/net/protocolhttp.cpp (hunk 2 above)
Comment (nekiro) [reply src/framework/net/protocolhttp.cpp:62]: answered in previous comment

**Review by libergod — APPROVED** [review]
PR #1341  will resolve the issues identified in the Build check jobs.

All builds passed GL, DX, and Debug. Tested with VS2022 Solution and CMake.
