### PR TITLE
fix: battlelist widget with Object Pool

### LINKED ISSUE #1245: Visual target bug when hiding battle list filter buttons
### Priority

Medium

### Area

- [x] Data
- [x] Source
- [ ] Docker
- [ ] Other

### What happened?

There is a clear bug that occurs whenever any of the battle list filter buttons are hidden (such as hide/show monsters, NPCs, or players).
Once a filter button is hidden, the target system starts displaying the wrong visual target — the target marker randomly jumps to other creatures, even though the actual target remains correct.

This causes immediate confusion during combat, since the displayed target does not match the actual one, making the player believe they are attacking one creature when they are actually attacking another.

I'm using Canary 1340 with the latest version of Redemption.
No error in the terminal.

https://github.com/user-attachments/assets/dffc54de-2996-4319-98a8-d7dc2c507e3e

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kokekanon**
# Description

To ensure that each reused button returns to its default appearance, implement the `resetObjectPool()` function within the `uicreaturebutton`.

With this adjustment, every button released and later retrieved from the ObjectPool will look identical to a newly created one, preventing visual inconsistencies like those described in this issue.  #1245

# Actual
Image

---------------------

>  |+

## fix: battlelist first  login ( without cache)

image

### CODE REVIEW

**Review by luanluciano93 — APPROVED** [review]

File: modules/gamelib/ui/uicreaturebutton.lua [hunk 1]
```diff
@@ -192,3 +192,19 @@ function UICreatureButton:updateIcons(icons)
     end
 end
 
+function UICreatureButton:resetObjectPool()
```
Comment (mehah) [inline modules/gamelib/ui/uicreaturebutton.lua]: UICreatureButton::resetState() would be better

**Review by mehah — CHANGES_REQUESTED** [review]
